name: Pull_Request Triage
description: Assign label to new PRs without a label
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - if:
          - payloadType: Pull_Request
          - and:
              - isOpen
              - not:
                  and:
                    - isAssignedToSomeone
                    - isLabeled
        then:
          - if:
              - bodyContains:
                  pattern: [x] Migrating and Modernizing Virtual Machines to Azure
            then:
              - addLabel:
                  label: MigrateVMs
          - if:
              - bodyContains:
                  pattern: [x] Upskilling Plan
            then:
              - addLabel:
                  label: UpskillingPlan
          - if:
              -not:
                and:
                  - bodyContains:
                      pattern: branch
                  - bodyContains:
                      pattern: permission
            then:
              - addLabel:
                  label: triage     