name: Issue Triage
description: Assign label to new issues without a label
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - if:
          - payloadType: Issues
              - isActivitySender:
                user: 'arclares_microsoft'
                issueAuthor: true # Optional
          - and:
              - isOpen
              - not:
                  and:
                    - isAssignedToSomeone
                    - isLabeled
        then:
           - addLabel:
                label: triage     
