name: Pull_Request Triage
description: Assign label to new PRs without a label
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - if:
          - payloadType: Pull_Request
          - and:
              - isOpen
        then:
          - addLabel:
                  label: MigrateVMs
